openapi: 3.0.3
info:
  title: 'Laravel 11 API Document'
  description: 'Auth and Task API '
  version: 1.0.0
servers:
  -
    url: 'https://378a-180-180-152-30.ngrok-free.app/laravel-crud-api/public'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route laravel-crud-api/public/api/user could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route laravel-crud-api/public/api/user could not be found.'
      tags:
        - Endpoints
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ygtlcevgoawiyjpmhpx
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: jarrod.price@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: t(bz8$C=Hr|xh
              required:
                - name
                - email
                - password
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: wlangworth@example.net
                password:
                  type: string
                  description: ''
                  example: omnis
              required:
                - email
                - password
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/tasks:
    get:
      summary: ''
      operationId: getApiTasks
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route laravel-crud-api/public/api/tasks could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route laravel-crud-api/public/api/tasks could not be found.'
      tags:
        - Endpoints
    post:
      summary: ''
      operationId: postApiTasks
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: x
                description:
                  type: string
                  description: ''
                  example: 'Nemo consectetur aut expedita ea.'
                status:
                  type: string
                  description: ''
                  example: in_progress
                  enum:
                    - pending
                    - in_progress
                    - completed
                due_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-10-11T12:34:23'
                priority:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 5.'
                  example: 4
              required:
                - title
                - status
                - priority
  '/api/tasks/{id}':
    get:
      summary: ''
      operationId: getApiTasksId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The route laravel-crud-api/public/api/tasks/1 could not be found.'
                properties:
                  message:
                    type: string
                    example: 'The route laravel-crud-api/public/api/tasks/1 could not be found.'
      tags:
        - Endpoints
    put:
      summary: ''
      operationId: putApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: bd
                description:
                  type: string
                  description: ''
                  example: 'Aut possimus pariatur sit sit cumque.'
                status:
                  type: string
                  description: ''
                  example: pending
                  enum:
                    - pending
                    - in_progress
                    - completed
                due_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2024-10-11T12:34:23'
                priority:
                  type: integer
                  description: 'Must be at least 1. Must not be greater than 5.'
                  example: 5
              required:
                - title
                - status
                - priority
    delete:
      summary: ''
      operationId: deleteApiTasksId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
